In [6]:
import numpy as np

In [5]:
#Creating Numpy Array

In [6]:
my_list = [1,2,3]

In [9]:
x = np.array(my_list)

In [10]:
type(x)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
type(1.00)

float

In [1]:
type(1)

int

In [2]:
type(1.0)

float

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10, 3)

array([ 0.,  5., 10.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5,5)

array([[4.35922465e-01, 4.67925153e-01, 1.08684986e-01, 9.73500839e-01,
        7.49221069e-01],
       [1.32797733e-01, 5.27566499e-01, 3.88631304e-01, 8.85172493e-01,
        6.34116339e-01],
       [7.58489839e-01, 8.82761755e-01, 4.29630897e-01, 9.24095906e-01,
        3.30592009e-01],
       [2.71086016e-01, 1.24466040e-02, 2.99857951e-01, 4.58698276e-04,
        7.75727614e-01],
       [7.20863910e-01, 2.65421794e-01, 4.86365686e-01, 6.11474554e-01,
        3.62004344e-01]])

In [24]:
np.random.randn(5,2)

array([[-1.91316932, -1.61147924],
       [-0.21433976,  1.12425954],
       [-0.08721789, -0.70252781],
       [-1.42735925,  0.95303849],
       [ 0.82879267,  0.23209079]])

In [28]:
np.random.randint(5)

3

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr

array([ 5, 34, 46, 15, 47,  7, 35, 14, 16, 13])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(5,5).shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')

In [39]:
ranarr

array([ 5, 34, 46, 15, 47,  7, 35, 14, 16, 13])

In [40]:
ranarr.max()

47

In [41]:
ranarr.argmax()

4

In [ ]:
ranarr