In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[2]

2

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:] = 200

In [19]:
arr_copy
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [21]:
# mat[row,col]
#mat[row][col]

In [22]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
mat[0]

array([ 5, 10, 15])

In [25]:
mat[2]

array([35, 40, 45])

In [26]:
mat[1][1]

25

In [27]:
mat[0][2]

15

In [28]:
mat[:2][1:]

array([[20, 25, 30]])

In [29]:
mat[:2][1:]

array([[20, 25, 30]])

In [30]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [32]:
arr = np.arange(1,11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr > 4

In [36]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])